<?php

$labels['login_failed'] = "Nextcloud Anmeldung fehlgeschlagen. Bitte versuche es sp&auml;ter erneut!";
$labels['logging_in'] = "Melde bei Nextcloud an.";
$labels['no_login_link'] = "Keinen Link empfangen. Bitte versuche es sp&auml;ter erneut.";
$labels['logged_in_reupload'] = "Erfolgreich bei Nextcloud angemeldet. Bitte denke daran die Datei erneut hochzuladen!";
$labels['login'] = "Anmelden";

$labels['file_too_big'] = "Datei zu gro&szlig;";
$labels['file_too_big_explain'] =
    "<p>Die Datei, die du versucht, hast hochzuladen ist zu gro&szlig; zum direkten anh&auml;ngen. Du kannst gro&szlig;e Dateien jedoch ".
    "zu Nextcloud hochladen und verlinken, indem du dein Nextcloud Konto unten verbindest.</p>".
    "<p><b>Bitte versuche Datei nach dem Anmelden erneut hochzuladen.</b></p>";


$labels['upload_success_link_inserted'] = "erfolgreich zu Nextcloud hochgeladen und Link eingef&uuml;gt";

$labels['upload_failed_title'] = "Nextcloud hochladen fehlgeschlagen";
$labels['upload_warning_title'] = "Nextcloud Warnung";
$labels['upload_failed'] = "Nextcloud hochladen fehlgeschlagen:";

$labels['missing_config'] = "Nextcloud Erweiterung ist nicht konfiguriert. Bitte kontaktiere den Administrator!";
$labels['cannot_mkdir'] = "Unterordner zum Hochladen konnte nicht erstellt werden:";
$labels['folder_access'] = "Es konnte nicht auf den Ordner zugegriffen werden! Bitte pr&uuml;fe die Berechtigungen oder frage einen Administrator";
$labels['cannot_find_unique_name'] = "Es konnte kein einzigartiger Dateiname gefunden werden. Versuche die Datei umzubenennen oder den Ordner in Nextcloud aufzur&auml;umen";
$labels['cannot_link'] = "Das hochladen der Datei war erfolgreich, es konnte aber kein Link erstellt werden. Bitte versuche manuell einen Link zu erstellen oder frage den Administrator.";

$labels['cloud_attachments'] = "Cloud Anh&auml;nge";
$labels['cloud_server'] = "Cloud Server";
$labels['status'] = "Status";
$labels['connected_as'] = "<b style='color: green'>Verbunden</b> als";
$labels['disconnect'] = "trennen";
$labels['connect'] = "verbinden";
$labels['not_connected'] = "Nicht verbunden";


