<?php

$labels['login_failed'] = "Nextcloud login failed. Please try again later!";
$labels['logging_in'] = "Logged-in to Nextcloud.";
$labels['no_login_link'] = "No login link received. Please try again later.";
$labels['logged_in'] = "Successfully logged-in to Nextcloud.";
$labels['login'] = "Login";
$labels['login_and_link_file'] = "Login and share Link";

$labels['file_too_big'] = "File Too Big";

$labels['file_too_big_not_logged_in_explain'] = "The file is larger then %limit% and can't be attached. After connecting the your Nextcloud account below, you may send it anyway, by sharing it as file-link instead.";

$labels['file_too_big_explain'] = "The file is larger then %limit% and can't be attached. You can share it as Nextcloud file-link instead.";

$labels['file_big'] = "How do You Want to Share the File?";
$labels['file_big_explain'] = "The file is quite large: %size%. You can keep your emails small by sharing it as a file-link instead.";
$labels['file_big_not_logged_in_explain'] = "The file is quite large: %size%. You can keep your emails small by connecting your Nextcloud account below and sharing it as a file-link instead.";

$labels['link_file'] = "Upload and share link";
$labels['attach'] = "Attach copy";

$labels['upload_success_link_inserted'] = "successfully uploaded to Nextcloud and link inserted";

$labels['upload_failed_title'] = "Nextcloud Upload Failed";
$labels['upload_warning_title'] = "Nextcloud Warning";
$labels['upload_failed'] = "Nextcloud Upload Failed:";

$labels['missing_config'] = "Nextcloud plugin config missing. Contact Admin!";
$labels['cannot_mkdir'] = "couldn't create sub folder for upload:";
$labels['folder_access'] = "Couldn't access upload folder! Check permissions or ask the admin";
$labels['cannot_find_unique_name'] = "couldn't find a unique upload filename. Try renaming the file or files in you Nextcloud folder";
$labels['cannot_link'] = "upload of file succeeded, but we couldn't create a share link. Try to create the link manually or ask the admin for assistance.";

$labels['cloud_attachments'] = "Cloud Attachments";
$labels['cloud_server'] = "Cloud Server";
$labels['status'] = "Status";
$labels['connected_as'] = "<b style='color: green'>Connected</b> as";
$labels['disconnect'] = "disconnect";
$labels['connect'] = "connect";
$labels['not_connected'] = "Not connected";


