<?php

$labels['login_failed'] = "Nextcloud login failed. Please try again later!";
$labels['logging_in'] = "Logged-in to Nextcloud.";
$labels['no_login_link'] = "No login link received. Please try again later.";
$labels['logged_in_reupload'] = "Successfully logged-in to Nextcloud. Please remember to re-upload the file!";
$labels['login'] = "Login";

$labels['file_too_big'] = "File too big";
$labels['file_too_big_explain'] =
    "<p>The file you tried to upload is too large. You can automatically upload large ".
    "files by connecting to your cloud storage blow.</p>".
    "<p><b>After connecting the storage, please try uploading the file again.</b></p>";


$labels['upload_success_link_inserted'] = "successfully uploaded to Nextcloud and link inserted";

$labels['upload_failed_title'] = "Nextcloud Upload Failed";
$labels['upload_warning_title'] = "Nextcloud Warning";
$labels['upload_failed'] = "Nextcloud Upload Failed:";

$labels['missing_config'] = "Nextcloud plugin config missing. Contact Admin!";
$labels['cannot_mkdir'] = "couldn't create sub folder for upload:";
$labels['folder_access'] = "Couldn't access upload folder! Check permissions or ask the admin";
$labels['cannot_find_unique_name'] = "couldn't find a unique upload filename. Try renaming the file or files in you Nextcloud folder";
$labels['cannot_link'] = "upload of file succeeded, but we couldn't create a share link. Try to create the link manually or ask the admin for assistance.";

$labels['cloud_attachments'] = "Cloud Attachments";
$labels['cloud_server'] = "Cloud Server";
$labels['status'] = "Status";
$labels['connected_as'] = "<b style='color: green'>Connected</b> as";
$labels['disconnect'] = "disconnect";
$labels['connect'] = "connect";
$labels['not_connected'] = "Not connected";


