<?php

$labels['login_failed'] = "Nextcloud login failed. Please try again later!";
$labels['logging_in'] = "Logging-in to Nextcloud.";
$labels['no_login_link'] = "No login link received. Please try again later.";
$labels['logged_in'] = "Successfully logged-in to Nextcloud.";
$labels['login'] = "Login";
$labels['login_and_link_file'] = "Login and share Link";

$labels['file_too_big'] = "File Too Big";

$labels['file_too_big_not_logged_in_explain'] = "The file is larger than %limit% and can't be attached. After connecting to your Nextcloud account below, you may send it anyway, by sharing it as file-link instead.";

$labels['file_too_big_explain'] = "The file is larger than %limit% and can't be attached. You can share it as Nextcloud file-link instead.";

$labels['file_big'] = "How do You Want to Share the File?";
$labels['file_big_explain'] = "The file is quite large: %size%. You can keep your emails small by sharing it as a file-link instead.";
$labels['file_big_not_logged_in_explain'] = "The file is quite large: %size%. You can keep your emails small by connecting your Nextcloud account below and sharing it as a file-link instead.";

$labels['link_file'] = "Upload and share link";
$labels['attach'] = "Attach copy";

$labels['upload_success_link_inserted'] = "Successfully uploaded to Nextcloud and link inserted";

$labels['upload_failed_title'] = "Nextcloud Upload Failed";
$labels['upload_warning_title'] = "Nextcloud Warning";
$labels['upload_failed'] = "Nextcloud Upload Failed:";

$labels['delete_ok'] = "File deleted from Nextcloud successfully";
$labels['delete_error_explain'] = "File deletion failed with the following reason code: <b>%reason%</b>. If you want to ignore the error, you can delete the file from the attachment list anyway.";
$labels['remove_attachment'] = "Remove Nextcloud Attachment";
$labels['remove_from_list'] = "Ignore and remove from list";
$labels['remove_from_nextcloud_question'] = "This is a Nextcloud attachment. Do want to delete it from Nextcloud as well? However, you will still need to remove the attachment from the message text yourself.";
$labels['remove_from_nextcloud'] = "Remove from Nextcloud";
$labels['keep_in_nextcloud'] = "Keep in Nextcloud, but remove from list";



$labels['missing_config'] = "Nextcloud plugin config missing. Contact Admin!";
$labels['cannot_mkdir'] = "couldn't create sub folder for upload:";
$labels['folder_access'] = "Couldn't access upload folder! Check permissions or ask the admin";
$labels['cannot_find_unique_name'] = "couldn't find a unique upload filename. Try renaming the file or files in you Nextcloud folder";
$labels['cannot_link'] = "upload of file succeeded, but we couldn't create a share link. Try to create the link manually or ask the admin for assistance.";

$labels['cloud_attachments'] = "Cloud Attachments";
$labels['cloud_server'] = "Cloud Server";
$labels['status'] = "Status";
$labels['connected_as'] = "Connected as";
$labels['disconnect'] = "disconnect";
$labels['connect'] = "connect";
$labels['not_connected'] = "Not connected";

$labels['folder_layout'] = "Folder Layout";
$labels['folder_layout_default'] = "Server default: ";
$labels['folder_layout_flat'] = "Everything in one folder";
$labels['folder_layout_hash'] = "Organize by leading file-hash bytes";
$labels['folder_layout_date'] = "Organize by date";
$labels['folder_layout_date_Y'] = "Organize by year";
$labels['folder_layout_date_Y/LLLL'] = "Organize by year and month";
$labels['folder_layout_date_Y/LLLL/dd'] = "Organize by year, month and week of month";
$labels['folder_layout_date_Y/LL'] = "Organize by year and month";
$labels['folder_layout_date_Y/LL/dd'] = "Organize by year, month and week of month";
$labels['folder_layout_date_Y/ww'] = "Organize by year and calendar week";
$labels['folder_layout_date_Y/ww/EEEE'] = "Organize by year, calendar week and weekday";
$labels['folder_layout_date_Y/ww/E'] = "Organize by year, calendar week and weekday";

$labels['password_protected_links'] = "Generate password protected Links";
$labels['expire_links'] = "Set expiry date for links";
$labels['expire_links_after'] = "Days to expire links after";

$labels['password'] = "Password";
$labels['valid_until'] = "Valid until";

$labels['filelink_attachment'] = "Filelink Attachment";
$labels['file_is_filelink_download_below'] = 'The file $filename was attached as a Filelink. It can be downloaded from the link below.';
$labels['size'] = "Size:";
$labels['link'] = "Link:";
$labels['checksum'] = "Checksum:";
$labels['available_until'] = "Available until:";
$labels['valid_until_expires'] = '$validuntil, after which the download link will expire';
$labels['attachment_disclaimer'] = 'Attachments hosted on $serverurl and subject to the server provider\'s terms of service and privacy policy. <b>Beyond the attachment becoming unavailable after the expiration date, the sender may delete the attachment at any point; download and save the file to retain a local copy.</b> Be careful who\'s attachments you trust, especially with executables and office documents.';
$labels['copyright'] = 'Generated with $repolocation for Roundcube by $author';
$labels['icons'] = "Icons:";
$labels['deletion'] = 'deletion';