<?php

$labels['login_failed'] = "Ошибка входа в Nextcloud. Пожалуйста, попробуйте позже!";
$labels['logging_in'] = "Вход в Nextcloud.";
$labels['no_login_link'] = "Ссылка для входа не получена. Пожалуйста, попробуйте позже.";
$labels['logged_in'] = "Успешный вход в Nextcloud.";
$labels['login'] = "Войти";
$labels['login_and_link_file'] = "Войти и поделиться ссылкой";

$labels['file_too_big'] = "Файл слишком большой";

$labels['file_too_big_not_logged_in_explain'] = "Файл превышает размер %limit% и не может быть прикреплен. После подключения к вашему аккаунту Nextcloud вы можете отправить его, поделившись ссылкой на файл.";

$labels['file_too_big_explain'] = "Файл превышает размер %limit% и не может быть прикреплен. Вы можете поделиться им как ссылкой на файл в Nextcloud.";

$labels['file_big'] = "Как вы хотите поделиться файлом?";
$labels['file_big_explain'] = "Файл довольно большой: %size%. Вы можете уменьшить размер писем, поделившись ссылкой на файл вместо его прикрепления.";
$labels['file_big_not_logged_in_explain'] = "Файл довольно большой: %size%. Вы можете уменьшить размер писем, подключившись к вашему аккаунту Nextcloud ниже и поделившись ссылкой на файл вместо его прикрепления.";

$labels['link_file'] = "Загрузить и поделиться ссылкой";
$labels['attach'] = "Прикрепить копию";

$labels['upload_success_link_inserted'] = "Успешно загружено в Nextcloud, и ссылка вставлена";

$labels['upload_failed_title'] = "Ошибка загрузки в Nextcloud";
$labels['upload_warning_title'] = "Предупреждение Nextcloud";
$labels['upload_failed'] = "Ошибка загрузки в Nextcloud:";

$labels['delete_ok'] = "Файл успешно удален из Nextcloud";
$labels['delete_error_explain'] = "Ошибка удаления файла код: %reason%. Вы можете оставить файл в списке вложений или удалить его автоматически.";
$labels['remove_attachment'] = "Удалить вложение Nextcloud";
$labels['remove_from_list'] = "Игнорировать и удалить из списка";
$labels['remove_from_nextcloud_question'] = "Это вложение из Nextcloud. Хотите удалить его из Nextcloud? Однако вам все равно придется удалить вложение из текста сообщения вручную.";
$labels['remove_from_nextcloud'] = "Удалить из Nextcloud";
$labels['keep_in_nextcloud'] = "Оставить в Nextcloud, но удалить из списка";



$labels['missing_config'] = "Отсутствует конфигурация плагина Nextcloud. Обратитесь к администратору!";
$labels['cannot_mkdir'] = "Не удалось создать подпапку для загрузки:";
$labels['folder_access'] = "Не удалось получить доступ к папке загрузки! Проверьте права доступа или обратитесь к администратору";
$labels['cannot_find_unique_name'] = "Не удалось найти уникальное имя файла для загрузки. Попробуйте переименовать файл или файлы в папке Nextcloud";
$labels['cannot_link'] = "Файл успешно загружен, но не удалось создать ссылку для общего доступа. Попробуйте создать ссылку вручную или обратитесь к администратору.";

$labels['cloud_attachments'] = "Облачные вложения";
$labels['cloud_server'] = "Облачный сервер";
$labels['status'] = "Статус";
$labels['connected_as'] = "Подключено как";
$labels['disconnect'] = "Отключить";
$labels['connect'] = "Подключено";
$labels['not_connected'] = "Нет подключения";

$labels['folder_layout'] = "Структура папок";
$labels['folder_layout_default'] = "Настройки сервера по умолчанию:";
$labels['folder_layout_flat'] = "Всё в одной папке";
$labels['folder_layout_hash'] = "Организация по хэш-байтам файла";
$labels['folder_layout_date'] = "Организация по дате";
$labels['folder_layout_date_Y'] = "Организация по годам";
$labels['folder_layout_date_Y/LLLL'] = "Организация по годам и месяцам";
$labels['folder_layout_date_Y/LLLL/dd'] = "Организация по годам, месяцам и неделям месяца";
$labels['folder_layout_date_Y/LL'] = "Организация по годам и месяцам";
$labels['folder_layout_date_Y/LL/dd'] = "Организация по годам, месяцам и неделям месяца";
$labels['folder_layout_date_Y/ww'] = "Организация по годам и календарным неделям";
$labels['folder_layout_date_Y/ww/EEEE'] = "Организация по годам, календарным неделям и дням недели";
$labels['folder_layout_date_Y/ww/E'] = "Организация по годам, календарным неделям и дням недели";

$labels['password_protected_links'] = "Создавать защищенные паролем ссылки";
$labels['expire_links'] = "Устанавливать срок действия ссылок";
$labels['expire_links_after'] = "Дней до истечения срока действия ссылок";

$labels['password'] = "Пароль";
$labels['valid_until'] = "Действительно до";




